Implement file's FileSystem API in node_io
pulyaevskiy/node-interop pull request #88
Opened 2020-11-17 03:41 UTC by nex3

Closes #86

2020-11-19 04:43 UTC, pulyaevskiy requested changes
LGTM, thanks! Just one minor comment in pubspec.

2020-11-19 04:43 UTC, pulyaevskiy commented on node_io/pubspec.yaml
> +  node_interop: {path: ../node_interop}
This is no longer needed, right?

2020-11-20 21:57 UTC, nex3 commented on node_io/pubspec.yaml
> +  node_interop: {path: ../node_interop}
Done.

2020-11-21 17:14 UTC, pulyaevskiy approved these changes
LGTM, thanks again!

2020-11-21 17:15 UTC, merged